version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.10  # Using a Python Docker image
    steps:
      - checkout  # Check out the code from the repository
      - setup_remote_docker  # Set up Docker in the CircleCI environment
      - run:
          name: Build and Push Docker Image
          command: |
            # Define the Docker image version using the CircleCI build number
            version="build-$CIRCLE_BUILD_NUM"
            echo "Building Docker image with tag: $version"
            
            # Build the Docker image
            docker build -t mounikajalari/capstoneproject:$version .
            
            # Log in to Docker Hub using environment variables
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            
            # Push the Docker image to Docker Hub
            docker push mounikajalari/capstoneproject:$version

workflows:
  version: 2  # Define the version of workflows syntax
  build_and_push_workflow:
    jobs:
      - build_and_push  # Run the build and push job
